# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reg_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meat_name', models.CharField(default='none', max_length=200)),
                ('product_type', models.CharField(choices=[('کیلوگرام', 'کیلوگرام'), ('تعداد', 'تعداد')], default='count', max_length=10)),
                ('reg_date', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('meat_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meats', to='product_and_catagory.catagories')),
            ],
        ),
    ]
