# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('تامین کننده', 'تامین کننده'), ('مشتری', 'مشتری'), ('هردو', 'هردو')], max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('total_balance', models.FloatField(blank=True, null=True)),
                ('date_issued', models.CharField(max_length=200)),
                ('due_date', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('پرداخت نه شده', 'پرداخت نه شده'), ('ّپرداخت شده', 'پرداخت شده'), ('رسید کامل', 'رسید کامل')], default='پرداخت نه شده', max_length=50)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('total_balance', models.FloatField(blank=True, null=True)),
                ('date_issued', models.CharField(max_length=200)),
                ('due_date', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('پرداخت نه شده', 'پرداخت نه شده'), ('ّپرداخت شده', 'پرداخت شده'), ('رسید کامل', 'رسید کامل')], default='پرداخت نه شده', max_length=50)),
                ('notes', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanss', to='Customer.customer')),
            ],
        ),
    ]
