# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='sale_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saless', to='Order.sale_item_part'),
        ),
        migrations.AddField(
            model_name='loan',
            name='sale_id_for_pay',
            field=models.ManyToManyField(blank=True, related_name='payed', to='Order.sale_item_part'),
        ),
        migrations.AddField(
            model_name='loan',
            name='sale_id_to_find_the_deletion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_deletion', to='Order.sale_item_part'),
        ),
        migrations.AddField(
            model_name='sloan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sloanss', to='Customer.customer'),
        ),
    ]
