# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('amount', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('reamin_amonts', models.IntegerField()),
                ('description', models.TextField(blank=True, help_text='Optional description for the expense', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the record was created')),
            ],
            options={
                'verbose_name': 'Fixed Expense',
                'verbose_name_plural': 'Fixed Expenses',
            },
        ),
        migrations.CreateModel(
            name='LoanApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datea', models.CharField(max_length=300)),
                ('amounta', models.IntegerField()),
                ('descriptiona', models.TextField(blank=True, help_text='Optional description for the expense', null=True)),
                ('expenses_foriengkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.fixedexpense')),
            ],
            options={
                'verbose_name': 'loan Expense',
                'verbose_name_plural': 'loan Expenses',
            },
        ),
    ]
