# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('product_and_catagory', '0001_initial'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouse_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('capacity_by_num', models.IntegerField()),
                ('current_stock', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('reg_date', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='tranfer_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.FloatField()),
                ('weight', models.FloatField()),
                ('product_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p', to='product_and_catagory.product')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_wareouse', to='warehouse.warehouse_info')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='warehouse.warehouse_info')),
            ],
        ),
        migrations.CreateModel(
            name='inventrories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.FloatField()),
                ('weight_field', models.FloatField()),
                ('in_and_out', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=3)),
                ('product_foerignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_foerignkey', to='product_and_catagory.product')),
                ('pucrchase_foerignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_foerignkey', to='purchase.parchase')),
                ('sale_forignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_forignkey', to='Order.sale_item_part')),
                ('warehouse_foerignkey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_foerignkey', to='warehouse.warehouse_info')),
            ],
        ),
    ]
