# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('total_unit', models.IntegerField()),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ضرب وزن', 'ضرب وزن'), ('ضرب تعداد', 'ضرب تعداد')], default='pending', max_length=20)),
                ('price_per_unit', models.FloatField()),
                ('wegiht', models.FloatField()),
                ('details', models.TextField(blank=True, null=True)),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
                ('remain_amount', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.IntegerField()),
                ('naem_of_giver', models.CharField(max_length=200)),
                ('date_of_giving', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='item_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_day', models.CharField(max_length=200)),
                ('number', models.FloatField()),
                ('weighht', models.FloatField()),
                ('status', models.CharField(choices=[('رسید', 'رسید'), ('برداشت', 'برداشت')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dealer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
    ]
