# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0003_initial'),
        ('product_and_catagory', '0001_initial'),
        ('purchase', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_deals',
            name='godam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse_info'),
        ),
        migrations.AddField(
            model_name='item_deals',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_and_catagory.product'),
        ),
        migrations.AddField(
            model_name='parchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_and_catagory.product'),
        ),
        migrations.AddField(
            model_name='parchase',
            name='supplaier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.customer'),
        ),
        migrations.AddField(
            model_name='parchase',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse_info'),
        ),
    ]
