# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coolaborators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.CharField(max_length=200, verbose_name='تاریخ')),
                ('name_opf', models.CharField(max_length=200, verbose_name='نام شریک')),
                ('phone_num', models.IntegerField(verbose_name='شماره موبایل')),
                ('adreess', models.CharField(max_length=200, verbose_name='آدرس')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='cuurency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curr_name', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='total_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_money_in_system', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='exchagn_money_in_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('want_amount', models.FloatField()),
                ('currency_that_will_chage_amount', models.FloatField()),
                ('currency_that_chage_amont', models.FloatField()),
                ('exchabge_rate', models.FloatField()),
                ('chaged_amont', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('currency_that_you_want_to_get_money', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_target', to='Finance_and_Accounting.cuurency', verbose_name='currency that want')),
                ('currency_that_you_want_tochage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_as_source', to='Finance_and_Accounting.cuurency', verbose_name='currency that change')),
            ],
        ),
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.CharField(max_length=200, verbose_name='تاریخ')),
                ('exchagne_rate', models.FloatField(blank=True, null=True)),
                ('income_amount', models.IntegerField(blank=True, null=True, verbose_name='مقدار دریافت')),
                ('total_incme_with_last_record', models.IntegerField(blank=True, null=True)),
                ('exchanged_moneey', models.IntegerField(blank=True, null=True)),
                ('descriiption', models.TextField(verbose_name='توضیحات')),
                ('is_income_or_outcome', models.CharField(choices=[('دریافت', 'دریافت'), ('پرداخت', 'پرداخت')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('blooelean_field', models.BooleanField(blank=True, null=True)),
                ('curr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finance_and_Accounting.cuurency', verbose_name='واحد پولی')),
                ('olabrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_and_Accounting.coolaborators', verbose_name='شریک')),
            ],
        ),
        migrations.CreateModel(
            name='outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_date', models.CharField(max_length=200, verbose_name='تاریخ')),
                ('out_come_amount', models.IntegerField(verbose_name='مقدار پرداخت')),
                ('descriiption', models.TextField(verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('olabrate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance_and_Accounting.coolaborators', verbose_name='شریک')),
            ],
        ),
    ]
