# Generated by Django 5.1.3 on 2026-01-02 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('product_and_catagory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_of_sale', models.CharField(max_length=500)),
                ('product_of_sale', models.CharField(max_length=500)),
                ('quantity_of_sale', models.CharField(max_length=500)),
                ('total_amount_of_sale', models.CharField(max_length=500)),
                ('price_per_unit_of_sale', models.CharField(max_length=500)),
                ('rerun_of_quantity', models.CharField(max_length=400)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('cancel', 'لغو شده'), ('complete', 'تکمیل شده')], default='pending', max_length=20)),
                ('total_amount', models.FloatField()),
                ('reg_date', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('price_per_unit', models.FloatField()),
                ('total_price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_and_catagory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.CharField(max_length=200)),
                ('total_paid_amount', models.FloatField(blank=True, null=True)),
                ('total_remain_amount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('price_per', models.IntegerField()),
                ('data', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='Order.sale')),
            ],
        ),
        migrations.CreateModel(
            name='order_loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_amount', models.IntegerField()),
                ('naem_of_giver', models.CharField(max_length=200)),
                ('date_of_giving', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='Order.sale')),
            ],
        ),
        migrations.CreateModel(
            name='sale_item_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('weight', models.FloatField()),
                ('should_paid', models.FloatField()),
                ('borrow_amount', models.FloatField()),
                ('status', models.CharField(choices=[('ضرب وزن', 'ضرب وزن'), ('ضرب تعداد', 'ضرب تعداد')], default='pending', max_length=20)),
                ('paid_amount_for_every_record', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_money_approved', models.BooleanField(default=False)),
                ('reamin_amount_according_to_sale_record', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='product_and_catagory.product')),
                ('sell_forei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.sale')),
            ],
        ),
    ]
